### ISSUE TITLE
Grammar?

### ISSUE THREAD

**Issue by CraigChilds94** [thejameskyle/the-super-tiny-compiler#16]
It'd be great if one of the inputs for the compiler was the grammar? or at least making the grammar for the language more clear in terms of how it's ensured in the program.

**Comment by thejameskyle** [comment]
Yeah, I've received the feedback that I need more examples of inputs/outputs.

I don't want to add any more complexity to the actual code though

**Comment by CraigChilds94** [comment]
@thejameskyle Great work though, it's super cool seeing stuff like this; reminds me of Uni
