### ISSUE TITLE
Should the `regex` be shortened?

### ISSUE THREAD

**Issue by sarbbottam** [thejameskyle/the-super-tiny-compiler#21]
Since `var WHITESPACE = /\s/;`, should `var NUMBERS = /[0-9]/;` be `var NUMBERS = /\d/;` and `var LETTERS = /[a-zA-Z]/;` be `var LETTERS = /[a-z]/i;`? Thanks!

**Comment by leeoniya** [comment]
`\d` is not equivalent to `[0-9]`: http://stackoverflow.com/a/16621778/973988

D:

**Comment by sarbbottam** [comment]
Interesting and thanks for the pointer. I'm not sure, if that is true in javascript
```js
// english 1-0 followed by bengali 1-0
'1234567890১২৩৪৫৬৭৮৯০'.match(/\d*/) // ["1234567890"]
```

**Comment by leeoniya** [comment]
Also interesting :)

**Comment by thejameskyle** [comment]
If someone wants to pr the `/[a-zA-Z]/` => `/[a-z]/i` that's fine, not a big deal either way
