### ISSUE TITLE
On regexps

### ISSUE THREAD

**Issue by phaistonian** [thejameskyle/the-super-tiny-compiler#31]
Not an issue, of course, but how about defining the RegExps (e.g WHITESPACE) once (at the beginning) so they don't get evaluated on each run?

Having them defined in one place will also bring some more clarity.

**Comment by thejameskyle** [comment]
Hi, I answered this question over here: https://github.com/thejameskyle/the-super-tiny-compiler/pull/22#issuecomment-204175311

Basically I'm not that concerned with optimization for the purposes of this project and having the regex right there makes it easier to walk through step by step, especially when I'm presenting this code in a talk.
