### ISSUE TITLE
Question: How to tell apart the different parenthesis?

### ISSUE THREAD

**Issue by AlastairTaft** [thejameskyle/the-super-tiny-compiler#33]
Not sure if this is the place to ask. Having had to write a compiler before, I still wonder what's the best way to handle the different parenthesis types.
 
Lets say you were compiling JavaScript, how do you know when it's used for function execution or order of operations e.g.

```javascript
var test = 2 * myFunc(3 + 4)
// or
var test = 2 * (3 + 4)
```

Seems to me function execution is always preceded by an identifier, but then does that mean you have to implement some sort of look back, or previous token variable in your parser. How far do you go with this, do you have a range of previous tokens?

I always thought 'look-back' feels like I'm doing something wrong.

**Comment by mrpudn** [comment]
Like you said, the `(` is immediately preceded by the identifier `myFunc` in the function call, while the `(` is immediately preceded by whitespace in the order of operations. That should tell you that you have a function and not, say, a variable - no "look-back" required.

When you encounter an identifier, you need to do some further inspection in order to determine whether you found yourself a variable, a function, a class, a struct, etc.

That's just my naive observation :)

**Comment by thejameskyle** [comment]
Oh sorry, I meant to respond to this but I decided to just write a follow up project that goes into more depth about parsers.

You often have to check the surrounding tokens to identify what one of them is for. Some parsers will also track the "state" of the tokens

**Comment by AlastairTaft** [comment]
Thanks for the replies. 

@mrpudn When you say no "look-back" required, but you have to know what comes before to determine what you've landed on. I guess you mean you don't have to look back back but you already have the previous tokens in memory that you can check.

@thejameskyle Cool, would be interested in reading that, especially any info you've got on tracking "state". Thanks for clarifying about checking surrounding tokens

**Comment by mrpudn** [comment]
Rather, I think you'd "look-ahead" in this case.

Maybe something like this (in `tokenizer()`):
```js
    // ...
    var IDENTIFIER_FIRST = /[A-Za-z_]/i; // non-numeric
    if (IDENTIFIER_FIRST.test(char)) {
      var value = input[++current];
      var IDENTIFIER = /[A-Za-z0-9_]/i;
      while (IDENTIFIER.test(char)) {
        value += char;
        char = input[++current];
      }
      char = input[current + 1]; // look-ahead
      if (char == '(') {
        tokens.push({
          type: 'identifier-function',
          value: value
        });
      } else if (/* ... */) {
        // ...
      }
      continue;
    }
    // ...
```

**Comment by mrpudn** [comment]
@AlastairTaft, after reflecting on this, this morning, I fear I've introduced too much scope into the tokenizer with my example.

I think you'd tokenize the input first, and then decide if you have a function, variable, etc. in later steps of the compilation process.

Here's just a simplified list of tokens that you might parse:
```js
tokens = ['var', 'test', '=', '2', '*', 'myFunc', '(', '3', '+', ',', '4', ')']
```

Then, you would notice that `(` follows the identifier `myFunc`, which means you've got a function and should reflect that in your AST.

Hope that helps!

**Comment by AlastairTaft** [comment]
Thanks @mrpudn. I get what you mean, I created a JS parser once and did use a tokenizer like you've done here. It's confiding knowing it isn't so straightforward because I had to think long and hard about how to do it, makes me feel less dumb.
