### ISSUE TITLE
unnecessary condition in parser ?

### ISSUE THREAD

**Issue by TaKaQod** [thejameskyle/the-super-tiny-compiler#34]
At the end of the parser there is this condition: 
`while (
        (token.type !== 'paren') ||
        (token.type === 'paren' && token.value !== ')')
)`

This condition is similar, right?
`while (
        (token.type !== 'paren') ||
        (token.value !== ')')
)`

Explanation of my logic:
> // So we create a `while` loop that will continue until it encounters a
>       // token with a `type` of `'paren'` and a `value` of a closing
>       // parenthesis.

**until**: (`type` of `'paren'`) **AND** (a `value` of a closing parenthesis)
equivalent to
**while**: (**NOT** `type` of `'paren'`) **OR** (**NOT** a `value` of a closing parenthesis)

If i just missed something, i'm curious to know what. ;)

ps: good tutorial, I learned some interesting things!!

**Comment by thejameskyle** [comment]
In a more complicated parser you could have other token types with a value of `')'` like a string type which would cause that logic to break

**Comment by TaKaQod** [comment]
if there is a `token.type === 'string'`, the first part of the condition will match whatever its value no?
so no loop break.
the only way to verify the second part of the condition is to have `token.type === 'paren'`.
And the only way to break so, is with `token.type === 'paren'` and `token.value=== ')'`


the token 
```
{
  type: 'string',
  value: ')'
}
```
matches  the condition 
_**(token.type !== 'paren')** || (token.value !== ')')_ 
on the first part, so no cheking for the second part and loops for this time.

i'm definitely thinking, this will not break.
