### ISSUE TITLE
How to create a tutorial like this?

### ISSUE THREAD

**Issue by fuaxio** [thejameskyle/the-super-tiny-compiler#46]
what did you use to make something like this like all the fancy decoration and stuff like that

**Comment by thejameskyle** [comment]
I'm not sure what you mean? I just wrote it...

**Comment by fuaxio** [comment]
Okay, how did you make all those fancy boxes and all the ascii art? also the data-structure.js had a graph of complexity. how did you plot that ? is there any vim plugin or emacs-mode that can help do these things i am not aware of?

**Comment by thejameskyle** [comment]
Lots and lots of manual work and copying from sites like chris.com

**Comment by zehrayla** [comment]
Zehrayla

**Comment by zehrayla** [comment]
Dosya

**Comment by zehrayla** [comment]
Zehrayla

**Comment by zehrayla** [comment]
Dosya

**Comment by zehrayla** [comment]
Zehrayla

**Comment by zehrayla** [comment]
Zehrayla@users
