### ISSUE TITLE
Possibly a bug: The header is too big

### ISSUE THREAD

**Issue by icy** [thejameskyle/the-super-tiny-compiler#47]
The introduction is very big. I think it's the bug because the compiler is expected to be (super) tiny.

See screenshot: https://s22.postimg.io/cnnp4nsg1/2016_09_18_220909_1474211349.png

**Comment by thejameskyle** [comment]
Cannot reproduce, works on my machine:

<img width="1440" alt="screen shot 2016-09-18 at 1 06 08 pm" src="https://cloud.githubusercontent.com/assets/952783/18618695/b9e707b0-7da0-11e6-93f7-13803e14b6fc.png">
