### ISSUE TITLE
Tokenizer issues

### ISSUE THREAD

**Issue by gsklee** [thejameskyle/the-super-tiny-compiler#52]
A few issues with the tokenizer:

1. The current number scanner will miss numbers in the form of `1e10`
2. The current string scanner will have issue with strings containing `\"`

I guess we don't wanna address corner cases like these in this project, but it'd be great to mention these inside the comment section.

**Comment by thejameskyle** [comment]
I don't think mentioning that adds much to the project, there's a lot of stuff that parsers would normally have to handle that this project does not even mention. The important bit is to understand how the ast gets put together.
